name: type_meter

description: A new Flutter project to calculate your typing speed.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For state management
  get: ^4.6.5

  # Share the link of app.
  share_plus: ^5.0.0

  # To launch website in device browser.
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  
  fonts:
    - family:  TMIcons
      fonts:
        - asset: assets/fonts/TMIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
