name: type_meter

description: A new Flutter project to calculate your typing speed.

publish_to: "none"

version: 1.0.0+0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For state management
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
