name: type_meter

description: A new Flutter project to calculate your typing speed.

publish_to: "none"

version: 1.0.0+0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For state management
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
