/// Flutter icons TMIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TMIcons
///      fonts:
///       - asset: fonts/TMIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class TMIcons {
  TMIcons._();

  static const _kFontFam = 'TMIcons';
  static const String? _kFontPkg = null;

  static const IconData github = IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest = IconData(0xf312, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf318, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spotify = IconData(0xf327, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf32d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData behance = IconData(0xf34e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
